# Generated by Django 5.0 on 2023-12-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
