# Generated by Django 5.0 on 2023-12-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
