# Generated by Django 5.0 on 2023-12-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('idx', models.IntegerField()),
                ('image', models.ImageField(upload_to='carousels/')),
            ],
        ),
    ]
