# Generated by Django 5.0 on 2023-12-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_userprofile_profile_picture'),
        ('myapp', '0009_contact'),
    ]

    operations = [
    ]
