# Generated by Django 3.2.12 on 2023-12-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_merge_20231219_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
